import '../../api/home/methods.js'
import '../../api/home/server/publications.js'
import '../../api/funktionen/methods.js'
import '../../api/funktionen/server/publications.js'
import '../../api/sogehts/methods.js'
import '../../api/sogehts/server/publications.js'
import '../../api/user_files/methods.js'
import '../../api/user_files/server/publications.js'
